### ISSUE TITLE
Update subscription context (e.g. uri, queryParams, etc.)

### ISSUE THREAD

**Issue by michelepatrassi** [kamilkisiela/apollo-angular#1201]
I would like to be able to change the context of a subscription before doing it via QueryRef::subscribeToMore and/or Apollo::subscribe.

### Use case
A user needs authentication on a websocket connection and a way to do this is to append a query parameter to the url (e.g. ws://192.168.0.0:8000?access_token=${token})). Currently there are two problems with this: refreshing the token is not possible, because uri and queryParams cannot be updated after initialization; accessing the token can be an async operation, and currently angular does not supports async providers (https://github.com/angular/angular/issues/23279).

With watchQuery change the http url is quite straighforward:
```
this.apollo.watchQuery({
      query: QUERY,
      context: {
        uri: 'https://github.com'
      }
    });
```
Cannot find the same way to do it for subscriptions. If the context would be available, it would be possible to get the async token and then do the subscription.

**Comment by kamilkisiela** [comment]
You can't change URL on context level because there's a single WebSocket connection for all requests. It's possible to do with regular queries and mutations because each translates to a new http request.

Because you're in charge of WebSocket Apollo Link, you can make it dynamic and change it based on context there. Apollo Angular does not own WS Link so nothing I can do in that topic.
