### ISSUE TITLE
apollo.d.ts update fails build

### ISSUE THREAD

**Issue by alisklixer** [kamilkisiela/apollo-angular#1491]
A build that passed friday (4/10/2020) before v1.9.0 failed after the update with the following error.

The line of code in apollo.d.ts has changed.
Private readonly client; has changed to private get client() .

Manually changing this line back builds the app successfully.

**Comment by Nisihitha** [comment]
Even i am facing same issue, please provide me the solution

**Comment by bogomips** [comment]
Hey, same issue here.

`
[ng] ERROR in node_modules/apollo-angular/Apollo.d.ts:26:17 - error TS1086: An accessor cannot be declared in an ambient context.
[ng] 26     private get client();
[ng]                    ~~~~~~
`

**Comment by kamilkisiela** [comment]
Please provide things like versions of TypeScript, Angular, Angular CLI etc, how do you use Apollo Angular and so on. More details.

**Comment by pickfire** [comment]
We have the same issue, our package.json is available in https://github.com/ctiteam/apspace/blob/master/package.json

**Comment by pickfire** [comment]
The issue is probably caused by having a public field becoming private. It probably could be solved by changing the field back to public.

https://github.com/apollographql/apollo-angular/blob/d2f3f56e9321b9c93d34913bff57993ec1bcdd57/packages/apollo-angular/src/Apollo.ts#L86-L90

I am curious why wasn't it a major release 2.0.0 when there is a breaking change in API since it uses semantic versioning.

**Comment by kamilkisiela** [comment]
@pickfire thank you for providing more details, like versions of typescript and angular packages :) Now I can fix it 👍

**Comment by kamilkisiela** [comment]
#1499 I will merge it and release it soon

**Comment by kamilkisiela** [comment]
[`v1.9.1`](https://github.com/kamilkisiela/apollo-angular/releases/tag/v1.9.1)
