### ISSUE TITLE
Unnecessary onChanges calls after update to v2

### ISSUE THREAD

**Issue by JesseZomer** [kamilkisiela/apollo-angular#1557]
**Describe the bug**

Lets say I have a list of items. Each item as a list of children. Whenever I do a mutation to add or remove something from the list of children, I do a read/writeQuery in the update function with the updated list. In apollo-angular v1 (apollo-client v2) this would only trigger the onChanges of the item that was changed + all his children. However in v2 (apollo-client v3) this triggers the onChanges of every item + every child.

**To Reproduce**
I've made a reproduction repo [here](https://github.com/JesseZomer/ac-onchanges). 
![image](https://user-images.githubusercontent.com/738579/92094592-eb9ce880-edd4-11ea-9687-37cafe646fe6.png)

To try it, cd into the server folder and do a `npm start`, then in another terminal do a `ng s` in the root.

The master branch is v2 (apollo-client v3). If you look in the console you can see messages for every time a component goes though onChanges. after a Click on a grandChild or the + to add a grandChild, you'll see every components onChanges gets triggered.

The `ac-v2` branch is v1 (apollo-client v2). If you click on a grandChild or on the + icon in this branch, you'll see only the affected child goes through the onChanges.

**Expected behavior**

I expect that even with apollo-angular v2 only the affected components onChanges will get called.

**Environment:**
See package.json depending on what branch you are.

**Additional context**

I'm using [shades](https://github.com/jamesmcnamara/shades) to do the immutable updates in the update function. The update function is the same on both branches. On the  `ac-v2` branch I've set `freezeResults` and `assumeImmutableResults` to `true`

**Comment by JesseZomer** [comment]
anybody willing to take a look?

**Comment by kamilkisiela** [comment]
@JesseZomer this is your component tree:

```html
<parent>
  <child>
    <grandchild />
 </child>
</parent>
```

You have a query in `parent` and both `child` and `grandchild` mutate data and after each mutation you update the query in `parent`.
Which means the query result updates and because you pass that result to `child` and then to `grandchild` components it means those have to rerender, because their inputs are different on each query update.

It has nothing to do with Apollo, it's a regular RxJS Observable + inputs + ngFor scenario. Nothing GraphQL/Apollo related.


Imagine this scenario. On every `click` within `child` and `grandchild` you emit a new array in the observable in `parent` component. The new array is not equal to the previous one, even by comparing each item, so from the angular perspective, it has to assume all the underlying components have to be re-rendered.

First of all, you should use `ngFor` and [`trackBy`](https://angular.io/api/common/NgForOf) to not recreate components all the time.

**Comment by kamilkisiela** [comment]
If you don't agree, feel free to @mention me here

**Comment by JesseZomer** [comment]
@kamilkisiela I'm using `trackBy` in my production app of course, left them out here because they didn't seem to make a difference.

If what you say is true, then how are we supposed to do a read/writeQuery in an update function, since updates there have to be immutable? 

Also that doesn't explain why it was working with version 1, as you can obviously see at the console.log statements. Only the affected components go through ngonchanges (as expected). The update function is the same on both branches.

**Comment by JesseZomer** [comment]
@kamilkisiela

**Comment by kamilkisiela** [comment]
I've got not much time to help you with this. Nothing has changed in Apollo Angular that may be related, it's mostly Apollo Client 3.0 that is a bit different than 2.0 version.

**Comment by JesseZomer** [comment]
@kamilkisiela to bad 😢 

Regardless it's still a big bug that needs to be addressed though. Imagine using apollo client for local state and updating a large list. Now for every change you make that does something to the list, every component goes through onChanges instead of just the parts you changed.

Unless you know of a way to use it in apollo-client 3? Maybe leave this issue open for people looking for the same problem?
