### ISSUE TITLE
error TS2307: Cannot find module 'react' or its corresponding type declarations.  1 import * as React from 'react';

### ISSUE THREAD

**Issue by jager** [kamilkisiela/apollo-angular#1722]
**Describe the bug**

After ng serve error occures:

```
Error: node_modules/@apollo/client/react/context/ApolloConsumer.d.ts:1:24 - error TS2307: Cannot find module 'react' or its corresponding type declarations.

1 import * as React from 'react';
```

**To Reproduce**

Instalation with ng add apollo-angular

**Environment:**

```
├── @angular/cli@12.2.10
├── @angular/core@12.2.10
├── @apollo/client@3.4.16
├── apollo-angular@2.6.0
├── graphql@15.7.2
└── typescript@4.3.5
```

**Comment by syrok0010** [comment]
The same on Angular 13

**Comment by Urigo** [comment]
Hi @jager and thank you for the report!

Sorry but I'm not adding a lot here but just labeling it according to our new Contribution Guide and [issue flow](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

It seems already got into `stage 0`.

Now in order to advance to `stage 1` we'll need a simple reproduction, maybe in code-sandbox? 

Later to progress to `stage 2`, a failing test would be needed, would be great if someone could help progress the issues through the [stages](https://github.com/the-guild-org/Stack/blob/master/CONTRIBUTING.md#a-typical-contributor-workflow).

Thank you and sorry that this comment is not a complete solution (yet).

**Comment by SimonBrazell** [comment]
This error occurred for me when trying to use the Apollo client from within an angular service, moving this code into a component instead resolved the issue. 

Not the best from a code reuse perspective... as a workaround I defined the queries and mutations in the shared service instead so at least I don't have to define them multiple times. 

Having a lot of issues implementing Apollo in an angular app for the first time, this being one of them.

**Comment by kamilkisiela** [comment]
Remember to use `@apollo/client/core` and not `@apollo/client`, we don't see any issue when using the correct import
