### ISSUE TITLE
Updating to `apollo-angular@3.0.0` produces  `error TS2307: Cannot find module 'apollo-angular/types' or its corresponding type declarations.`

### ISSUE THREAD

**Issue by KeithGillette** [kamilkisiela/apollo-angular#1756]
**Describe the bug**
Release 3.0.0 introduces an undocumented breaking change by moving the import location of types from `apollo-angular/types` to `apollo-angular/build/types` or `apollo-angular/src/types`.

**To Reproduce**
Update an `angular-apollo@2.x.x` project importing types, such as `import { QueryOptionsAlone, SubscriptionOptionsAlone, WatchQueryOptionsAlone } from 'apollo-angular/types';`.

**Expected behavior**
The import location should not change or [the Migration Guide](https://apollo-angular.com/docs/migration) should specify the new import location.

**Environment:**
```
├── @angular/cli@13.2.4 
├── UNMET PEER DEPENDENCY @angular/core@13.2.3 
├── @apollo/client@3.5.9 
├── @types/graphql@14.5.0
├── apollo-angular@3.0.0 
├── barrel-maintainer@1.5.3
├── graphql@16.3.0 
└── typescript@4.5.5 
```

**Additional context**
Thanks for the new release!

**Comment by grenobnik** [comment]
I confirm this problem.  Passing from v3.0.0-alpha.2 to v3 I lost some imports
```
Cannot find module 'apollo-angular/types' or its corresponding type declarations.
import { MutationResult } from 'apollo-angular/types';
```

**Comment by kamilkisiela** [comment]
It's not a public API, so it's not a breaking change. If you wish to have some types available directly in `apollo-angular`, please create a PR.

**Comment by KeithGillette** [comment]
Thanks for your reply, @kamilkisiela. I suppose that changing the import location of typings is not technically a breaking change according to Semantic Versioning, but doing so still breaks consuming applications so think it deserves some mention in the Migration Guide or release notes. Regardless, I don't care much where the types are imported from, but it seems they are available in 2 locations in 3.0.0, per my original post. Which is the correct location from which to import them?

**Comment by kamilkisiela** [comment]
Sure but it's never been a public API and if somebody used a "private" import to access a type than it's obvious it may change over time. What if I would move the type from `types.ts` to `service-types.ts`? Same story. It's not meant to be used, that's my point.

Imagine accessing an internal function of graphql-js:

```typescript
import { assertType } from 'graphql/type/definition';
```

It's there but it's a deep import and just an artifact of `tsc` and project's file structure. The `assertType` is not available publicly, through `graphql`, which means it's private and not intended to be used.

What if I would want to use it in let's say `graphql-tools`? I would create a Pull Request to make it a part of public API. Why? Because at some point graphql-js will change it's file structure because of many reasons.

**Comment by kamilkisiela** [comment]
People overused deep imports of `graphql` just because it was there and now Ivan and other maintainers can't change anything there because a lot of projects depend on it.

**Comment by KeithGillette** [comment]
I guess I'm confused how the types formerly in `apollo-angular/types` could be considered "private" since they are used to type the public API that is exposed to the consuming application. For example, `QueryOptionsAlone` is the type for the `options` parameter of the `fetch` method of `Query`. `Query.fetch` is a public method [described in the documentation](https://apollo-angular.com/docs/data/services#api-of-query).

**Comment by kamilkisiela** [comment]
```typescript
import { QueryOptionsAlone } from 'apollo-angular/types'
  vs
import { QueryOptionsAlone } from 'apollo-angular'
```

See the difference? The fact that `QueryOptionsAlone` is not exported in `apollo-angular` makes it "private". I can change the name of it any day and it won't affect any user using the public API available in `apollo-angular`.

`Query.fetch` which is public would work the same way as before, it would have the same options, the same shape but the type would have a different name.

Another example is `QueryRef`, it's intended to be public, it's available through `apollo-angular` import, but you could access it as well in v2 via `apollo-angular/query-ref`. 
Let's say now in v3 I decided to move `QueryRef` into `query.ts` file because it makes more sense. It won't break anyone using `apollo-angular` import.
Because it's public API and I let people use it, I know I can't change the name of `QueryRef` to `QueryReference`.

If somebody at some point created a Pull Request to expose these `*Alone` types in `apollo-angular` import, it would mean, it's now public, nobody can't change it.

Now another example, `fromPromise` function. You could import it like this:

```typescript
import { fromPromise } from 'apollo-angular/utils';
```

It's there because I use it in other files but does it mean I can't move it to other file because it would break some people? In my opinion no.

The difference between `fromPromise` and `QueryOptionsAlone` is that the `QueryOptionsAlone` is "closer" to public API than the `fromPromise` function.

```typescript
// Non-existing code but it should give you an idea what I mean by "closer".

export function publicFunction(options: QueryOptionsAlone) { // you "touch" options (2nd level, publicFunction is 1st level)
  return fromPromise(execute(option)); // but `fromPromise` is right after the options are touched (3rd level)
}
```

The `QueryOptionsAlone` type is not reference anywhere in the documentation as well.

See my point?

**Comment by kamilkisiela** [comment]
Another example:
https://github.com/kamilkisiela/apollo-angular/blob/dee1c98a97181378f969b480d45a048abee522e1/packages/apollo-angular/src/types.ts#L12

It's there, maybe somebody is using it but it's not documented, not intended to be used and not publicly available. 
You might say that `EmptyObject` is way less relevant than `QueryOptionsAlone` but for me it's the same from the maintenance perspective. It's internal.

**Comment by kamilkisiela** [comment]
And somebody could at some point could create exactly the same github issue as this one saying he/she used `EmptyObject`.

If you depend on this type, please create a Pull Request so the type could be publicly available and considered when planning breaking changes.

**Comment by KeithGillette** [comment]
Thanks for your detailed explanations, @kamilkisiela. I see your distinction that the _shape_ of `QueryOptionsAlone` is public but the _name and location_ of the particular type `QueryOptionsAlone` interface is private, or at least less public. As a library producer/maintainer, I can see why you might want to treat it as such. I hope you can appreciate why, as library consumer, I may want such second-level types to be public so I can easily reuse them to annotate my own code. From a consumer perspective, I see a big difference between the second level of parameter and return types and a third level of interior types not directly connected to any public API. Clearly the third level of private objects and their typings unconnected to the public API is none of my business. However, since the second level is tied directly to the public API in typing parameters and return types, I think a reasonable argument can be made for them to be part of the public API (and am curious how much of them not always being treated as such is an artifact of ECMAScript not supporting types natively and TypeScript layering on an optional type system). For what it's worth, I'm used to importing such second-level typings from other TypeScript libraries, notably those that this one unites, `@angular` and `apollo/client`, both of which export parameter and return type typings in their subpackages, though perhaps they are not technically considered public in those libraries, either.

**Comment by kamilkisiela** [comment]
These sub-packages are fine, these are public as well, take for example `apollo-angular/http`. It's documented, it's designed to be used this way.

I will create a Pull Request to export `*Alone` options and all these 2nd level types in `apollo-angular`.

**Comment by PowerKiKi** [comment]
I'm assuming this has been solved in the past few months...
