### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'architect')

### ISSUE THREAD

**Issue by chriswoodie** [kamilkisiela/apollo-angular#2046]
**Describe the bug**
Running `nx g apollo-angular:ng-add` results in the following error after providing graphql api url and graphql version:

```
TypeError: Cannot read properties of undefined (reading 'architect')
    at getMainPath (/Users/myuser/Documents/foo/node_modules/apollo-angular/schematics/utils/project.js:10:21)
```

**To Reproduce**

1. Create a Nx project
2. Create an angular application (not sure if this step is needed)
3. Run `npm install apollo-angular`
4. Run `nx g apollo-angular:ng-add`, fill in the questions that appear
5. See error

**Expected behavior**

Not an error to be thrown.

**Environment:**

├── @angular/cli@16.0.6
├── @angular/core@16.0.6
├── @apollo/client@3.7.16
├── apollo-angular@5.0.0
├── graphql@16.7.1
└── typescript@5.0.4

**Additional context**

None

**Comment by Kaemmelot** [comment]
The problem seems to be in multi-project angular applications. In [this line](https://github.com/kamilkisiela/apollo-angular/blob/f9671d286af46eb512825d3039957fe09e9672ec/packages/apollo-angular/schematics/utils/project.ts#L28) the `defaultProject` is undefined because it [was deprecated quite some time ago](https://github.com/angular/angular-cli/issues/20661) and is now [finally removed via migrations](https://github.com/angular/angular-cli/blob/a0bf9462f55da8873bc0c6a16d2109b82dd4d704/packages/schematics/angular/migrations/migration-collection.json#L6).
So the default project should be determined based on the working directory and not based on the `angular.json` file.

**Comment by PowerKiKi** [comment]
I _think_ it might have been fixed in the past months. Please re-open if still experienced with latest version.
